### ISSUE TITLE
建议增加下载进度回调显示

### ISSUE THREAD

**Issue by inteai** [mofada/flutter_update_app#1]
组件非常好用,如果能增加下载进度回调显示就更好了.

**Comment by mofada** [comment]
感谢你的肯定, 后面我会考虑增加进度的, 谢谢

**Comment by inteai** [comment]
感谢您的付出。

**Comment by i5yi** [comment]
> 感谢你的肯定，后面我会考虑增加进度的，谢谢

组件简单易用，就是缺少进度回调，比如当前下载进度、下载完成、下载失败等回调信息
