### ISSUE TITLE
对于未引入kotlin的项目报错

### ISSUE THREAD

**Issue by yhz199132** [mofada/flutter_update_app#2]
* Where:
Build file '/Users/yhz/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/update_app-0.1.2/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':update_app'.
> Plugin with id 'kotlin-android' not found.

**Comment by mofada** [comment]
创建这个项目主要是自用, 最近也没有时间去维护, 可能要晚点才有时间看了

**Comment by mofada** [comment]
现在还有这个问题吗?

**Comment by yhz199132** [comment]
我自己项目引入kotlin支持就可以使用了，因为项目中没有用到kotlin所以开始没有引入。 379008118 邮箱：379008118@qq.com 签名由 网易邮箱大师 定制 在2020年03月20日 16:00，fada mo 写道： 现在还有这个问题吗? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mofada** [comment]
好的, 那我关闭啦
