### ISSUE TITLE
运行报错了

### ISSUE THREAD

**Issue by zhangweiwei0326** [mofada/flutter_update_app#3]
/Users/weiwei/Documents/byapp/android/app/src/debug/AndroidManifest.xml:51:13-64 Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(com.huaronghz.hs.fileprovider) from AndroidManifest.xml:51:13-64
	is also present at [:update_app] AndroidManifest.xml:22:13-66 value=(com.huarong.hs.updateprovider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml to override.
/Users/weiwei/Documents/byapp/android/app/src/debug/AndroidManifest.xml:56:13-47 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/file_paths) from AndroidManifest.xml:56:13-47
	is also present at [:update_app] AndroidManifest.xml:27:17-52 value=(@xml/update_path).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

FAILURE: Build failed with an exception.

**Comment by mofada** [comment]
好像是两个的provider冲突了, 如果是这样的话那么我需要去掉FileProvider, 然后让你们自己配置了

**Comment by zhangweiwei0326** [comment]
现在能解决么 用了编译不过去

**Comment by mofada** [comment]
你现在很急吗? 这里我想是我的问题, 我稍后处理一下

**Comment by mofada** [comment]
更新一下依赖试试, 今天上午更新了一下插件

**Comment by zhangweiwei0326** [comment]
编译了一下是可以了，谢谢
