### ISSUE TITLE
监听下载完成广播

### ISSUE THREAD

**Issue by taozhipeng1990** [mofada/flutter_update_app#6]
我点击下载后，就顶部通知栏有下载的图标。
但下载完成后，不会自动打开文件。
而在调用下载时，无法获取到储存的位置。
我要如何在下载完后，打开呢

**Comment by mofada** [comment]
有监听下载的广播, 当下载完成以后会自动打开app安装

**Comment by taozhipeng1990** [comment]
是需要配置什么吗？
在文档中没有看到
我是一个新手菜鸟

**Comment by taozhipeng1990** [comment]
![image](https://user-images.githubusercontent.com/3894069/85984718-26bd1d00-ba1c-11ea-8306-4c8cf5ca4c46.png)

**Comment by mofada** [comment]
不需要进行任何的配置, 直接使用即可, 你现在使用的是哪个版本呢?

**Comment by taozhipeng1990** [comment]
```
  bool flag = await UpdateApp.updateApp(
                                    url: info.url, appleId: null, title: "大路演");
                                if (flag) {
                                  Toast.show("下载完成", context);
                                }
```
无法发图片，
请大佬指点一下，怎么监听下载完成的广播。
或推荐一下相关的文章。

**Comment by taozhipeng1990** [comment]
0.1.5

**Comment by mofada** [comment]
看下你的日志

**Comment by taozhipeng1990** [comment]
我这边下载完成后，什么反应都没有。
是要申请什么权限吗？
当前手机是华为meta 20

**Comment by mofada** [comment]
下载完成以后, 会自动弹出安装的提示框

**Comment by mofada** [comment]
不需要配置权限, 存储在app缓存目录

**Comment by taozhipeng1990** [comment]
V/AudioManager( 5860): querySoundEffectsEnabled...
W/roadshowing.dly( 5860): type=1400 audit(0.0:5930781): avc: granted { read open } for pid=5860 path="/mnt/media_rw/0123-4567/Android/data/com.roadshowing.dly/files/apks" dev="mmcblk1p1" ino=22549365 scontext=u:r:untrusted_app_27:s0:c103,c257,c512,c768 tcontext=u:object_r:exfat:s0 tclass=dir
W/System.err( 5860): java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/0123-4567/Android/data/com.roadshowing.dly/files/apks/com.jiuqi.news_2.0.1.apk
W/System.err( 5860): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
W/System.err( 5860): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
W/System.err( 5860): 	at cn.mofada.update_app.UpdateUtilKt.installApk(UpdateUtil.kt:112)
W/System.err( 5860): 	at cn.mofada.update_app.UpdateReceiver.downloadComplete(UpdateReceiver.kt:53)
W/System.err( 5860): 	at cn.mofada.update_app.UpdateReceiver.onReceive(UpdateReceiver.kt:20)
W/System.err( 5860): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4327)
W/System.err( 5860): 	at android.app.ActivityThread.access$2500(ActivityThread.java:292)
W/System.err( 5860): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2225)
W/System.err( 5860): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err( 5860): 	at android.os.Looper.loop(Looper.java:213)
W/System.err( 5860): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
W/System.err( 5860): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5860): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err( 5860): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by mofada** [comment]
好像是出现错误了, 我得看看

**Comment by taozhipeng1990** [comment]
大佬是不是下载保存时与完成后打开文件的路径不一致。
我在手机中是能看到这个文件的 /Android/data/com.roadshowing.dly/files/apks
但我看 java报错，好像找的路径不一样

**Comment by taozhipeng1990** [comment]
能加下微信或QQ吗？方便发截图。
QQ 414111907

**Comment by taozhipeng1990** [comment]
我手机有插内存卡。是否是因为这个原因

**Comment by taozhipeng1990** [comment]
大佬 还没修复吗？

**Comment by mofada** [comment]
晚点看看, 最近在忙

**Comment by mofada** [comment]
你这个问题后面怎么样啦
