### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by McCrafterIV** [mofada/flutter_update_app#8]
Would it be possible to add null safety support to make this dependency work with the newest version of dart?

**Comment by McCrafterIV** [comment]
See #9

**Comment by mofada** [comment]
Okay, received, I am going to release a new version

**Comment by McCrafterIV** [comment]
Thank you!

**Comment by mofada** [comment]
I’m a little sorry, I haven’t released it yet. It’s a bit difficult to release the version in China. I set the proxy of v2ray and it still doesn’t work. It shows error code 69. I need to rest. I will try it tomorrow.

**Comment by McCrafterIV** [comment]
I can use directly from git. Good luck 👍
